title: 2025 Combustion Early Career Investigator Workshop
description: Workshop for early career faculty and investigators in combustion and fire research.

theme: jekyll-theme-cayman
url: https://combustion-community.github.io/workshop-2025/
